[rocm-4.4] resolve -Werror -Wreorder complain
The original code triggers complain from compiler if
-Werror -Wreorder CXX_FLAGS are set. For example:
src/collectives/device/primitives.h:315:47:
error: field 'dsts' will be initialized after field 'connIndex'
[-Werror,-Wreorder-ctor]

This patch fixes it.